name: 同步 Schema

on:
  push:
    branches:
      - main

env:
  COS_VERSION: v0.11.0-beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@v3

      - name: 缓存
        uses: actions/cache@v3
        id: cache
        with:
          path: '~/.cache'
          key: ${{ env.COS_VERSION }}

      - name: 安装 coscli
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache
          wget https://github.com/tencentyun/coscli/releases/download/${{ env.COS_VERSION }}/coscli-linux
          mv ./coscli-linux ~/.cache/coscli
          chmod +x ~/.cache/coscli
          cat > ~/.cache/cos.yml << EOF
          cos:
            base:
              secretid: ${{ secrets.COS_SECRETID }}
              secretkey: ${{ secrets.COS_SECRETKEY }}
              sessiontoken: ""
            buckets:
              - name: ${{ secrets.COS_BUCKET }}
                alias: default
                region: ap-guangzhou
              - name: ${{ secrets.COS_BUCKET }}
                alias: accelerate
                region: accelerate
          EOF

      - name: 同步
        run: |
          ~/.cache/coscli cp ./schema cos://accelerate/schema -r -c ~/.cache/cos.yml
